R2 166 strip down useless models or processes from invoke ai docker image
resleeve/InvokeAI pull request #1
Opened 2023-03-20 14:16 UTC by vaidehiResleeve

@rhuet-resleeve I have pushed the changes here. Could you check this PR by building the docker with these changes?

2023-03-22 11:16 UTC, rhuet-resleeve requested changes
Currently being stuck in a loop, please have a look at what is happening and please change accordingly

2023-03-23 08:51 UTC, vaidehiResleeve commented
I have resolved the issue by copying few stuff in the docker file. Going forward we will not be requiring these changes as we will not be using their models for generation.

2023-03-23 08:59 UTC, rhuet-resleeve requested changes
I let some comments, no need to build a new image, it is simply to have a cleaner dockerfile

2023-03-23 08:59 UTC, rhuet-resleeve commented on docker/Dockerfile
> +# RUN --mount=type=cache,target=${PIP_CACHE_DIR} \
don't comment, just remove, the original is available in the original invoke ai repo if need be

2023-03-23 08:59 UTC, rhuet-resleeve commented on docker/Dockerfile
> +LABEL org.opencontainers.image.authors=
remove the line altogether?

2023-03-23 08:59 UTC, rhuet-resleeve commented on invokeai/frontend/CLI/CLI.py
> +    # transformers.logging.set_verbosity_error()
just remove the line

2023-03-23 08:59 UTC, rhuet-resleeve commented on invokeai/frontend/CLI/CLI.py
> +    # diffusers.logging.set_verbosity_error()
just remove the line

2023-03-23 08:59 UTC, rhuet-resleeve commented on invokeai/frontend/CLI/CLI.py
> +    # ModelManager.migrate_models()
just remove the line and the comment above "migrate...."

2023-03-23 08:59 UTC, rhuet-resleeve commented on invokeai/frontend/CLI/CLI.py
> +        # gen.load_model()   # this part of the code loads the weights. Hence commented.
remove the whole preload the model stuff, nothing is happening here anymore

2023-03-23 13:31 UTC, vaidehiResleeve commented on docker/Dockerfile
> +# RUN --mount=type=cache,target=${PIP_CACHE_DIR} \
removed the commented lines.

2023-03-23 13:32 UTC, vaidehiResleeve commented on docker/Dockerfile
> +LABEL org.opencontainers.image.authors=
removed the commented lines.

2023-03-23 13:32 UTC, vaidehiResleeve commented on invokeai/frontend/CLI/CLI.py
> +    # transformers.logging.set_verbosity_error()
removed the commented lines.

2023-03-23 13:32 UTC, vaidehiResleeve commented on invokeai/frontend/CLI/CLI.py
> +    # diffusers.logging.set_verbosity_error()
removed the commented lines.

2023-03-23 13:32 UTC, vaidehiResleeve commented on invokeai/frontend/CLI/CLI.py
> +        # gen.load_model()   # this part of the code loads the weights. Hence commented.
removed the commented lines.

2023-03-23 13:32 UTC, vaidehiResleeve commented on invokeai/frontend/CLI/CLI.py
> +# def invoke_ai_web_server_loop(gen: Generate, gfpgan, codeformer, esrgan):
removed the commented lines.

2023-03-23 13:33 UTC, vaidehiResleeve commented
@rhuet-resleeve I have made the changes as per your comments. Could you please have a look?

2023-03-23 13:47 UTC, merged