added metrics for inference/InvokeAI
resleeve/InvokeAI pull request #6
Opened 2023-04-04 16:11 UTC by luca-brg

Code to track the metrics

2023-04-06 07:57 UTC, vaidehiResleeve commented on invokeai/backend/generate.py
maybe remove the space.

2023-04-06 07:57 UTC, vaidehiResleeve commented on invokeai/backend/generate.py
> +
this space as well

2023-04-06 07:59 UTC, vaidehiResleeve commented on invokeai/backend/generate.py
> +
remove space here as well.

2023-04-07 06:37 UTC, vaidehiResleeve commented on invokeai/backend/generate.py
> +            # We don't support anymore keyboard interruption.
just a question : why is the significance of these two comments?

2023-04-07 06:38 UTC, vaidehiResleeve requested changes
Just few spaces here and there.

2023-04-07 06:46 UTC, luca-brg commented on invokeai/backend/generate.py
> +            # We don't support anymore keyboard interruption.
It was to explain why we are not handling this error. But considering this part of code is never triggered anymore we could just consider removing it.

2023-04-07 06:50 UTC, luca-brg commented on invokeai/backend/generate.py
Fixed it

2023-04-07 06:50 UTC, luca-brg commented on invokeai/backend/generate.py
> +
Done.

2023-04-07 06:50 UTC, luca-brg commented on invokeai/backend/generate.py
> +
And done.

2023-04-07 09:05 UTC, vaidehiResleeve commented on invokeai/backend/generate.py
> +            # We don't support anymore keyboard interruption.
maybe we can keep this comment for now and later review if we want to implement or not.

2023-04-07 09:06 UTC, vaidehiResleeve approved these changes
approved

2023-04-07 11:17 UTC, merged